/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BagsRouteImport } from './routes/bags'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as RightsRouteImport } from './routes/rights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsRoute = BagsRouteImport.update({
  id: '/bags',
  path: '/bags',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bags': typeof BagsRoute
  '/family': typeof FamilyRoute
  '/learn': typeof LearnRoute
  '/rights': typeof RightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bags': typeof BagsRoute
  '/family': typeof FamilyRoute
  '/learn': typeof LearnRoute
  '/rights': typeof RightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bags': typeof BagsRoute
  '/family': typeof FamilyRoute
  '/learn': typeof LearnRoute
  '/rights': typeof RightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bags' | '/family' | '/learn' | '/rights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bags' | '/family' | '/learn' | '/rights'
  id: '__root__' | '/' | '/bags' | '/family' | '/learn' | '/rights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagsRoute: typeof BagsRoute
  FamilyRoute: typeof FamilyRoute
  LearnRoute: typeof LearnRoute
  RightsRoute: typeof RightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags': {
      id: '/bags'
      path: '/bags'
      fullPath: '/bags'
      preLoaderRoute: typeof BagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagsRoute: BagsRoute,
  FamilyRoute: FamilyRoute,
  LearnRoute: LearnRoute,
  RightsRoute: RightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
